version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - 1337:1337
    volumes:
      - ./server:/server:ro
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui/src:/app/src:ro
      - /ui/src/node_modules
    ports:
      - 3000:3000
    

