export const PARTICIPANT_LIST_REQUEST = 'PARTICIPANT_LIST_REQUEST'
export const PARTICIPANT_LIST_SUCCESS = 'PARTICIPANT_LIST_SUCCESS'
export const PARTICIPANT_LIST_FAIL = 'PARTICIPANT_LIST_FAIL'

export const PARTICIPANT_DETAILS_SAVE = 'PARTICIPANT_DETAILS_SAVE'
export const PARTICIPANT_DETAILS_CLEAR = 'PARTICIPANT_DETAILS_CLEAR'
export const PARTICIPANT_UPDATE_SUBMIT_TIME = 'PARTICIPANT_UPDATE_SUBMIT_TIME'