export const PARTICIPANT_LIST_REQUEST = 'PARTICIPANT_LIST_REQUEST'
export const PARTICIPANT_LIST_SUCCESS = 'PARTICIPANT_LIST_SUCCESS'
export const PARTICIPANT_LIST_FAIL = 'PARTICIPANT_LIST_FAIL'

export const PARTICIPANT_DETAILS_REQUEST = 'PARTICIPANT_DETAILS_REQUEST'
export const PARTICIPANT_DETAILS_SUCCESS = 'PARTICIPANT_DETAILS_SUCCESS'
export const PARTICIPANT_DETAILS_FAIL = 'PARTICIPANT_DETAILS_FAIL'

export const PARTICIPANT_DELETE_REQUEST = 'PARTICIPANT_DELETE_REQUEST'
export const PARTICIPANT_DELETE_SUCCESS = 'PARTICIPANT_DELETE_SUCCESS'
export const PARTICIPANT_DELETE_FAIL = 'PARTICIPANT_DELETE_FAIL'

export const PARTICIPANT_CREATE_REQUEST = 'PARTICIPANT_CREATE_REQUEST'
export const PARTICIPANT_CREATE_SUCCESS = 'PARTICIPANT_CREATE_SUCCESS'
export const PARTICIPANT_CREATE_FAIL = 'PARTICIPANT_CREATE_FAIL'
export const PARTICIPANT_CREATE_RESET = 'PARTICIPANT_CREATE_RESET'

export const PARTICIPANT_UPDATE_REQUEST = 'PARTICIPANT_UPDATE_REQUEST'
export const PARTICIPANT_UPDATE_SUCCESS = 'PARTICIPANT_UPDATE_SUCCESS'
export const PARTICIPANT_UPDATE_FAIL = 'PARTICIPANT_UPDATE_FAIL'
export const PARTICIPANT_UPDATE_RESET = 'PARTICIPANT_UPDATE_RESET'

export const PARTICIPANT_WAITTIME_REQUEST = 'PARTICIPANT_WAITTIME_REQUEST'
export const PARTICIPANT_WAITTIME_SUCCESS = 'PARTICIPANT_WAITTIME_SUCCESS'
export const PARTICIPANT_WAITTIME_FAIL = 'PARTICIPANT_WAITTIME_FAIL'

export const PARTICIPANT_LISTALL_REQUEST = 'PARTICIPANT_LISTALL_REQUEST'
export const PARTICIPANT_LISTALL_SUCCESS = 'PARTICIPANT_LISTALL_SUCCESS'
export const PARTICIPANT_LISTALL_FAIL = 'PARTICIPANT_LISTALL_FAIL'
