export const SURVEY_DETAILS_REQUEST = 'SURVEY_DETAILS_REQUEST'
export const SURVEY_DETAILS_SUCCESS = 'SURVEY_DETAILS_SUCCESS'
export const SURVEY_DETAILS_FAIL = 'SURVEY_DETAILS_FAIL'
export const SURVEY_DETAILS_CLEAR = 'SURVEY_DETAILS_CLEAR'